Adding UI tests for eShop on AWS
radius-project/samples pull request #378
Opened 2023-06-27 18:56 UTC by ytimocin

The goal of this PR is to add UI tests for eShop on AWS. Here is the [link](https://github.com/project-radius/samples/tree/v0.21/reference-apps/eshop#aws-infrastructure) to the eShop on AWS reference app.

1. Added `AWS CLI Download` step
2. Added `AWS Login` step
3. Added `Create EKS Cluster` step
4. Updated the step that registers credentials for the given environment
5. Added eShop on AWS to the test matrix
6. Added a step to delete the EKS Cluster created for the test

ToDo:
1. ~~We need to add AWS-related secrets to the pipeline: `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY`.~~ **Added by @AaronCrawfis**

2023-07-05 18:39 UTC, shalabhms approved these changes

2023-07-05 22:07 UTC, AaronCrawfis requested changes

2023-07-24 22:01 UTC, AaronCrawfis requested changes
Couple small notes but is overall looking good

2023-08-30 19:40 UTC, AaronCrawfis approved these changes

2023-09-08 17:30 UTC, closed without merging