Fix Dapr microservices sample
radius-project/samples pull request #654
Opened 2023-10-20 09:55 UTC by ASHIQUEMD

### This PR fixes below Dapr microservices sample issue

On running `rad run dapr.bicep`, it throws below error.

`No application was specified. Use --application to specify the application name.`

2023-10-20 16:13 UTC, AaronCrawfis commented
Thanks @ASHIQUEMD! The .rad folder is a great addition to the samples repo to be able to quickly clone and run.

@willtsai could you take a look and make sure this lines up with the sample and the instructions? I noticed we have the application defined in the dapr.bicep file. We can probably remove that from the file and move to the .rad folder instead to match the convention we've been following in the getting started guide and new app tutorial. We also should make sure the app name is consistent throughout the docs as well.

2023-10-25 21:27 UTC, willtsai requested changes
Thank you @ASHIQUEMD for the contribution! I believe the application name in `.rad` must match the application name defined in the Bicep files, so I made a suggestion. please let me know if it makes sense.

@AaronCrawfis - I will create a separate PR to edit the [Dapr Tutorial](https://docs.radapp.io/tutorials/dapr/) in the Documentation to leverage `.rad` for application name.

Let me know if you have additional questions.

2023-10-25 21:27 UTC, willtsai commented on samples/dapr/.rad/rad.yaml
> +  application: "dapr-app"
The application name in the bicep definition is just `dapr`

```suggestion
  application: "dapr"
```

2023-10-25 22:26 UTC, willtsai commented
corresponding changes to the tutorial in the documentation: https://github.com/radius-project/docs/pull/913

2023-10-30 18:26 UTC, willtsai commented
@ASHIQUEMD -- two things:
1. Can you please update your commit message to include a signoff so that this PR may fulfill the [DCO](https://github.com/radius-project/samples/pull/654/checks?check_run_id=18196293890) requirements?
2. Please take a look at my minor suggestion and commit it in if you agree.

Thanks again for your contribution!

2023-11-13 19:30 UTC, willtsai commented
@ASHIQUEMD -- can you please take a look at my suggestions and provide your DCO signoff on this PR so that we may get it committed and merged? Thank you!

2023-12-04 19:25 UTC, willtsai approved these changes

2023-12-04 20:06 UTC, merged